### ISSUE TITLE
try.haxe.org cpp / neko / php

### ISSUE THREAD

**Issue by delahee** [HaxeFoundation/Project-Management#39] opened 2015-07-06 14:13 UTC
Hi !

I believe the try.haxe.org tool could be vastly improved if it allowed to run other targets ! I don't know the difficulty but I guess running in a chrooted, rightless env could not harm ?

It would at least help us evangelist to jsut says, hey, you know it just works, you can try it  !

@clemos @simn ?

**Comment by waneck** [comment] 2015-07-06 14:18
I've actually been working on `compilehaxe.com` right in this moment. It will provide a REST API that any site like try Haxe can use. It'll allow to use multiple files, and to compile and run all targets.

This is also the base for the `learn haxe` website (which is the reason why I'm working on it right now)

**Comment by back2dos** [comment] 2015-07-06 14:20
@waneck That sounds awesome!

**Comment by markknol** [comment] 2015-07-06 15:43
This is kind of a duplicate of https://github.com/HaxeFoundation/Project-Management/issues/16

**Comment by delahee** [comment] 2015-07-06 16:18
Duplicate of #16

**Closed as completed** 2015-07-06 16:18 UTC
